### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1855631630",
  "amount": 500
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "abfedc96bd9d4d41a40ed92943e790d9",
  "accountNumber": "1855631630",
  "amount": 500
}
